In [2]:
from sklearn.metrics import pairwise_distances

# Setup

%load_ext autoreload
%autoreload 2

import os

import torch
import numpy as np
from umap import UMAP
from torch.nn.functional import normalize
from dotenv import load_dotenv
from pandas import read_json
from sklearn.cluster import HDBSCAN
from transformers import AutoModel, AutoTokenizer

from pipelines.multi_service.pooling_layer import mean_pooling

load_dotenv()

print(f"HuggingFace cache directory is {os.environ.get('HF_HOME')}")


def should_be_skipped(class_name: str):
    return (
        class_name.endswith("Test")
        or class_name.endswith("Tests")
        or class_name.endswith("IT")
    )

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


HuggingFace cache directory is /media/martin/BigData/datasets/cache/huggingface/


In [9]:
import pandas as pd

# MODEL = "google-bert/bert-base-uncased"
# MODEL = "google-bert/bert-base-cased"
GENERIC_WORDS = [
    "get",
    "set",
    "find by",
    "exists by",
    "exists",
    "update",
    "delete",
    "delete by",
    "create",
    "get all",
    "insert",
    "insert into",
    "find all",
    "find all by",
    "remove",
    "add",
    "edit",
    "save",
    "list",
    "view",
]
# Sort by length descending to ensure "find all by" is matched before "find all"
GENERIC_WORDS.sort(key=len, reverse=True)

MODEL = "microsoft/codebert-base"
# MODEL = "microsoft/graphcodebert-base"

codeBertTokenizer = AutoTokenizer.from_pretrained(MODEL)
codeBertModel = AutoModel.from_pretrained(MODEL)

# bertTokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")
# bertModel = AutoModel.from_pretrained("google-bert/bert-base-uncased")

# input_file = "/media/martin/BigData/datasets/pa165-git/01/multi-service.jsonl"
# output_file = "/media/martin/BigData/datasets/pa165-git/01/multi-service-result.jsonl"

input_file = (
    "/media/martin/BigData/datasets/github-projects/klaw/multi-service-labeled.jsonl"
)
output_file = (
    "/media/martin/BigData/datasets/github-projects/klaw/final-with-centroids.jsonl"
)

# input_file = "/media/martin/BigData/datasets/github-projects/cas/multi-service.json"
# output_file = "/media/martin/BigData/datasets/github-projects/cas/multi-service-result-codebert-combined.jsonl"

input_file = "/media/martin/BigData/datasets/pa165-git/multi-service-filtered-labeled-evaluated.jsonl"
output_file = (
    "/media/martin/BigData/datasets/pa165-git/multi-service-with-distances.jsonl"
)

data_frame = read_json(input_file, lines=True)

# origin_property = "methodSignature"
# evaluation_property = "methodSignatures"


def extract_property(methods: list[dict[str, str]], property: str):
    return list(map(lambda m: m[property], methods))


def remove_words(text: str):
    for word in GENERIC_WORDS:
        if text.startswith(word):
            text = text.removeprefix(word).strip()

    return text


def evaluate(inputs: list[dict[str, str]], _fully_qualified_name: str):
    # class_name = fully_qualified_name.split(".")[-1]
    signature = extract_property(inputs, "signature")
    # cls_with_signature = list(
    #     map(
    #         lambda signature: "class " + class_name + " { \n " + signature + " {} \n}",
    #         signature,
    #     )
    # )
    mean_pooled_signature = get_embeddings(signature)
    # method_names = extract_property(inputs, "name")
    # method_name_split = list(
    #     map(lambda name: remove_words(" ".join(split_camel_case(name))), method_names)
    # )
    # mean_names = get_embeddings(method_name_split)

    signature_normalized = normalize(mean_pooled_signature, p=2, dim=1)
    # name_normalized = normalize(mean_names, p=2, dim=1)

    # combined = torch.cat((signature_normalized, name_normalized), dim=-1)
    mean_pooled_numpy = signature_normalized.cpu().numpy()

    # pca = PCA(n_components=0.95, random_state=42)
    # pca_reduced = pca.fit_transform(mean_pooled_numpy)

    umap = UMAP(
        n_neighbors=5,
        min_dist=0.0,
        n_components=15,
        metric="euclidean",
        random_state=42,
        init="random",
    )
    umap_reduced = umap.fit_transform(mean_pooled_numpy)
    # gap_df = calculate_gap_statistic(
    #     pca_reduced, n_refs=5, max_k=math.ceil(math.sqrt(len(inputs)))
    # )

    clustering_alg = HDBSCAN(
        min_samples=1,
        min_cluster_size=3,
        metric="euclidean",
        allow_single_cluster=True,
        store_centers="medoid",
    )

    labels = clustering_alg.fit_predict(umap_reduced)

    unique_labels = set(labels)
    number_of_clusters = len(unique_labels) - (1 if -1 in unique_labels else 0)
    noise_count = list(labels).count(-1)
    noise_ratio = noise_count / len(labels)
    # return (get_optimal_k_programmatically(gap_df)["optimal_k"], pca_reduced)

    print(labels)
    print(clustering_alg.medoids_)
    medoids = clustering_alg.medoids_
    unique_clusters = unique_labels - {-1}
    avg_distance = 0.0
    if len(unique_clusters) > 1:
        # centroids = []
        # for label in unique_clusters:
        #     centroids.append(np.mean(umap_reduced[labels == label], axis=0))

        if len(unique_clusters) > 1:
            distances = pairwise_distances(medoids, metric="cosine")
            print(distances)
            tri_offset = np.triu_indices(distances.shape[0], k=1)
            unique_distances = distances[tri_offset]

            avg_distance = np.mean(unique_distances)

            # distances = pairwise_distances(centroids, metric="euclidean")
            # tri_offset = np.triu_indices(distances.shape[0], k=1)
            # unique_distances = distances[tri_offset]
            #
            # # 5. Calculate Metrics
            # avg_distance = np.mean(unique_distances)
            # max_distance = np.max(unique_distances)
            # normalized_avg_distance = avg_distance / max_distance

    if all(x == -1 for x in labels):
        number_of_clusters = -1

    return (
        number_of_clusters,
        noise_ratio,
        labels,
        avg_distance,
    )


def get_embeddings(inputs, tokenizer=codeBertTokenizer, model=codeBertModel):
    inputs = list(map(lambda input: "<decoder-only> " + input, inputs))

    tokenized_inputs = tokenizer(
        inputs, return_tensors="pt", padding=True, truncation=True, max_length=512
    )
    with torch.no_grad():
        output = model(**tokenized_inputs)
    attention_mask = tokenized_inputs["attention_mask"]
    return mean_pooling(output, attention_mask)

    # return output.last_hidden_state[:, 0, :]


data_frame["optimal_k"] = pd.Series()
data_frame["noise_ratio"] = pd.Series()
data_frame["cluster"] = pd.Series()
data_frame["avg_dist"] = pd.Series(dtype="float64")
results = []
for index, row in data_frame.iterrows():
    class_name = row["fullyQualifiedName"]
    methods = row["methods"]

    if len(methods) < 10:
        print(f"Skipped small class {class_name}, number of methods {len(methods)}")
        continue

    if should_be_skipped(class_name):
        print(f"Skipped Test class {class_name}, number of methods {len(methods)}")
        continue

    optimal_k, noise_ratio, labels, avg_dist = evaluate(methods, class_name)

    # kmeans = KMeans(n_clusters=optimal_k, random_state=42)
    # cluster = kmeans.fit_predict(pca_reduced)
    data_frame.loc[index, "optimal_k"] = optimal_k
    data_frame.loc[index, "avg_dist"] = avg_dist * 100
    data_frame.loc[index, "noise_ratio"] = noise_ratio
    # data_frame.at[index, "cluster"] = cluster.tolist()
    data_frame.at[index, "cluster"] = labels

    results.append(f"{class_name}: {optimal_k}, {labels}, dist: {avg_dist:.4f}")

for result in results:
    print(result)

data_frame.to_json(output_file, lines=True, orient="records")

Skipped small class cz.muni.fi.pa165.services.beanMapping.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.pa165.services.accountCredentials.PasswordHashingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.pa165.services.itemtype.ItemTypeServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.services.accountCredentials.CredentialsFormatValidatorImpl, number of methods 2
Skipped small class cz.muni.fi.pa165.services.account.AccountServiceImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.services.item.ItemServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.services.image.ImageServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.facades.AccountFacadeImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.services.comment.CommentServiceImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.facades.ItemCreationFacade, number of methods 2
Skipped small class cz.fi.muni.pa165.

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0]
[[6.80760765 4.80724621 7.91290522 4.43225288 8.34120274 2.53096342
  4.17011786 9.27436924 6.21720028 3.44474316 7.4472909  4.42148018
  3.95347166 4.92707348 4.55130291]]
Skipped small class cz.fi.muni.pa165.winery.service.PersonServiceImpl, number of methods 9
Skipped small class cz.fi.muni.pa165.project.InitialData, number of methods 1
Skipped small class cz.muni.fi.pa165.data.DataLoadingFacadeImpl, number of methods 1
Skipped small class muni.pa165.rest.config.JwtTokenUtil, number of methods 5
Skipped small class muni.pa165.rest.interceptors.JWTFilter, number of methods 0
Skipped small class muni.pa165.api.facade.EventFacade, number of methods 7
Skipped small class muni.pa165.api.facade.CourtFacade, number of methods 5
Skipped small class muni.pa165.api.facade.ParticipantFacade, number of methods 6
Skipped small class cz.muni.fi.pa165.airportmanager.facade.FlightTemplateFacade, number of methods 5
Skipped small class cz.muni.fi.pa165.airportmanager.serv

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[ 0  0 -1 -1  0  0  0  0  0  0  0]
[[1.82514942 2.7712009  8.2039032  5.44341564 1.442963   1.40029001
  1.33752465 9.65287209 9.51103687 3.36014795 6.24074268 3.69124866
  5.66083002 2.95933104 0.92548639]]
Skipped small class cz.idomatojde.services.TimetableChatMessageServiceImpl, number of methods 4
Skipped small class cz.idomatojde.services.OfferPopularityServiceImpl, number of methods 2
Skipped small class cz.idomatojde.services.UserServiceImpl, number of methods 6
Skipped small class cz.idomatojde.services.OfferServiceImpl, number of methods 7
Skipped small class cz.idomatojde.services.facades.TimetableFacadeImpl, number of methods 7
Skipped small class cz.idomatojde.services.facades.CategoryFacadeImpl, number of methods 1


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0]
[[ 6.32466984  3.11352396  9.45378876  3.12649012  6.14299107  9.18709755
   5.64807034  4.13735342  2.48878646  2.90392399  1.26912487  9.66746998
  11.04500294  7.93048048  2.36570907]]
Skipped small class cz.idomatojde.services.CategoryServiceImpl, number of methods 1
Skipped small class cz.idomatojde.services.facades.UserFacadeImpl, number of methods 8


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 4 4 4 0 0 0 0 0 1 1 1 1 4 3 4 3 4 3 4 1 1 2 2 2 2]
[[ 4.46535349  4.55795956  3.06351185  2.43212914  6.59767389  4.25912046
   4.90525341  4.37802601  5.70888233  3.66706657  2.84764504  6.67852354
   2.52527666  5.8259654   2.62001276]
 [ 8.35860062  2.50084662  3.14196777  2.61296177  6.55549479  0.63469541
  11.1821661   2.91109848 10.18556118  3.135113    9.0728035   1.92960227
   4.12224197  9.61762047  3.69332552]
 [ 9.63385296  3.08375764  3.18487859  2.94693685  6.2102375   0.30889761
  11.57335186  3.44173455 10.25012493  2.85864878  9.12713623  1.62896013
   4.99325514  9.99174881  3.26365113]
 [ 4.4776144   5.3610301   4.35760784  5.0000658   4.51365376  3.12378716
   4.02122593  2.63516331  6.71680784  2.95792246  6.78581572  4.17443943
   5.03467178  7.27075195  4.89844322]
 [ 4.87613678  6.473001    4.70404816  5.12342501  4.69559908  2.77797103
   4.56945992  2.75568652  6.31586456  3.03605866  7.30350494  3.89776325
   5.72251749  6.89469719  4.67514229]]
[[0.

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[ 2.24984574  2.01286888  7.6194663   0.50806069  3.18171    10.61473274
  17.2497406   5.68130064 10.01154995 -2.72186089  5.50410795  4.05401421
   1.73117077  9.62573051  2.69294286]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[ 0  0  0  0  0 -1  0  0  0  0  0  0]
[[5.03710747 7.03739882 8.80743027 1.97119367 4.01030016 7.62411356
  5.64748621 6.80077791 4.26419401 2.78712511 5.1047411  3.297786
  4.14450312 3.76999974 9.66393089]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[ 2.24984574  2.01286888  7.6194663   0.50806069  3.18171    10.61473274
  17.2497406   5.68130064 10.01154995 -2.72186089  5.50410795  4.05401421
   1.73117077  9.62573051  2.69294286]]
Skipped small class cz.muni.fi.pa165.service.facade.UserFacadeImpl, number of methods 9
Skipped small class cz.muni.fi.pa165.service.facade.IngredientFacadeImpl, number of methods 6
Skipped small class cz.muni.pa165.barbershop.restreact.security.UserDetailsServiceImpl, number of methods 1
Skipped small class cz.muni.pa165.barbershop.restreact.security.JwtUtils, number of methods 3
Skipped small class cz.muni.pa165.barbershop.restreact.security.AuthEntryPointJwt, number of methods 1
Skipped small class cz.muni.fi.pa165.mvc.controllers.WineController, number of methods 8
Skipped small class cz.muni.fi.pa165.mvc.controllers.UserController, number of methods 8
Skipped small class cz.muni.fi.pa165.mvc.controllers.OrderController, number of methods 4
Skipped small class cz.muni.fi.pa

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0]
[[0.89781743 2.36002541 1.22776568 2.99982333 9.49993229 8.93864822
  9.837286   1.46311557 8.8422966  4.85870409 7.90963793 5.1790843
  2.48026276 5.83376646 0.25253558]]
Skipped small class muni.pa165.services.UserService, number of methods 8
Skipped small class muni.pa165.services.ParticipantService, number of methods 6
Skipped small class muni.pa165.services.facade.UserFacadeImpl, number of methods 8
Skipped small class cz.muni.fi.PA165.barbershop.service.facade.ServiceFacadeImpl, number of methods 6
Skipped small class cz.muni.fi.PA165.barbershop.service.ServiceServiceImpl, number of methods 6
Skipped small class cz.muni.fi.PA165.barbershop.service.EmployeeServiceImpl, number of methods 2
Skipped small class cz.muni.fi.PA165.barbershop.service.facade.ReservationFacadeImpl, number of methods 9
Skipped small class cz.muni.fi.PA165.barbershop.service.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.PA165.barbershop.service.facade.Employ

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[7.64783335 2.73269224 3.95561147 3.24014831 3.42553258 4.38732481
  6.79407787 7.07596016 9.05212688 0.63196266 1.33766842 5.89538288
  4.31081629 1.53594148 0.86273515]]
Skipped small class cz.fi.muni.pa165.service.BeanMapper, number of methods 3
Skipped small class cz.fi.muni.pa165.service.BeanMapperImpl, number of methods 3


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 1 1 0 0 0 0 0]
[[ 1.94321418 12.22412014  8.39998436  4.6113987   2.5618155   4.936584
   0.37583593  6.07510996  7.0662179  11.16024017 10.88171005  2.79501176
   6.72251034  5.35032034  6.82222795]
 [ 8.41053486 -2.28150082  3.28875995 13.99226284  2.33021092 11.10797596
  13.12637997  4.4079442   7.37675238  6.73181629 11.05958462 -0.44561079
   1.31023753 10.57053089  6.0712781 ]]
[[0.         0.37815467]
 [0.37815467 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 1 1 0 0 0]
[[ 7.09060717  7.97514915  9.00668049  3.30516052 12.22252941 14.4147501
  -1.2545501  11.31121063  0.96519256 -1.59579194 -5.34921932  3.34826875
   7.04762459 -6.29070091  1.53603315]
 [ 4.82013464  3.35605145  0.28231549 -4.80749989  1.92494738  7.13116407
   7.16454315 10.10537434 10.879426   12.78152561  3.14738131  3.53679967
   3.95307255  5.06435394  3.83147955]]
[[0.         0.63004283]
 [0.63004283 0.        ]]
Skipped small class cz.fi.muni.pa165.service.CommentaryService, number of methods 6
Skipped small class cz.fi.muni.pa165.service.CommentaryServiceImpl, number of methods 6


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 1 1 0 0 0]
[[ 7.09060717  7.97514915  9.00668049  3.30516052 12.22252941 14.4147501
  -1.2545501  11.31121063  0.96519256 -1.59579194 -5.34921932  3.34826875
   7.04762459 -6.29070091  1.53603315]
 [ 4.82013464  3.35605145  0.28231549 -4.80749989  1.92494738  7.13116407
   7.16454315 10.10537434 10.879426   12.78152561  3.14738131  3.53679967
   3.95307255  5.06435394  3.83147955]]
[[0.         0.63004283]
 [0.63004283 0.        ]]
Skipped small class cz.fi.muni.pa165.service.facade.CommentaryFacadeImpl, number of methods 6


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 1 0 0 0 1]
[[ 1.0578618   9.32455826 11.53364086  3.64551282  0.55758601  7.07655859
   6.20801115  2.30964947  1.88346839  3.82841754  6.5949626   3.50087023
  11.69881821  6.88268185  6.11510038]
 [ 0.63856292  8.2798996  12.1600523   4.45463657  0.57516819  7.18770695
   5.67842627  2.37145805  2.79662132  4.04017258  5.79004812  3.45303249
  10.91366768  7.57975197  6.43150806]]
[[0.         0.00428085]
 [0.00428085 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 1 0 0 0 1]
[[ 1.0578618   9.32455826 11.53364086  3.64551282  0.55758601  7.07655859
   6.20801115  2.30964947  1.88346839  3.82841754  6.5949626   3.50087023
  11.69881821  6.88268185  6.11510038]
 [ 0.63856292  8.2798996  12.1600523   4.45463657  0.57516819  7.18770695
   5.67842627  2.37145805  2.79662132  4.04017258  5.79004812  3.45303249
  10.91366768  7.57975197  6.43150806]]
[[0.         0.00428085]
 [0.00428085 0.        ]]
Skipped small class cz.fi.muni.pa165.service.RatingService, number of methods 6
Skipped small class cz.fi.muni.pa165.service.RatingServiceImpl, number of methods 6


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[7.64783335 2.73269224 3.95561147 3.24014831 3.42553258 4.38732481
  6.79407787 7.07596016 9.05212688 0.63196266 1.33766842 5.89538288
  4.31081629 1.53594148 0.86273515]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 0 0 1 1 1 0 0 0 0]
[[6.26891375 1.23236895 8.3885479  3.82733083 4.77683306 6.2168951
  8.85318089 6.01171732 7.33934259 4.21290302 1.57099795 2.2070961
  6.76230955 6.9752903  4.43755722]
 [6.80286074 0.91398698 7.14211226 4.67579222 5.21207285 7.43644381
  7.11207962 5.50325537 7.90238333 4.69972801 1.26427722 3.14623189
  7.48217821 7.14843988 3.69855404]]
[[0.         0.01028904]
 [0.01028904 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0]
[[ 1.48804414  4.56155872  2.91038728  8.46125126  0.18586963  5.41934443
   2.13675261  4.86620569  3.61500478  8.68140602  6.04196262 -1.47998667
   8.18557262  2.33885813  1.01033843]]
Skipped small class cz.fi.muni.pa165.winery.utils.DatabaseCleaner, number of methods 1


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 1 1 1 1 1]
[[ 1.68837237  3.92136884  4.73523045  8.50700092  4.61479521  2.14261985
  -3.29338455 12.10788918  6.26349974  6.62480497  0.92254299  5.77628803
   4.15022135  1.13652861 -4.39484501]
 [10.88661098 12.08695412 10.60168552 -0.36397916  9.34771538  1.63755655
  12.71978569  3.17630959 -3.25279522 -3.57393622  1.53905439  7.667243
   5.31208801 11.74880981 14.13282299]]
[[0.         0.81317213]
 [0.81317213 0.        ]]
Skipped small class cz.fi.muni.pa165.project.facade.AirplaneFacadeImpl, number of methods 8
Skipped small class cz.fi.muni.pa165.project.service.StewardServiceImpl, number of methods 9


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 1 0 1 1 1 1]
[[ 3.54359388  5.66601753  9.02262592  4.96096945  0.80548441  8.06174755
   2.90861773  2.94476295  6.91996622 -2.25893283  0.6145249   8.37671375
   5.50544977 12.40572929  0.15592682]
 [ 5.30474663 -0.18629502  6.29853678  8.93909073  0.63234133  1.99268508
   2.75474691  1.7030673  12.14494133  1.81853318  0.1354319  12.54833603
   3.3871417   7.87410116  0.94113165]]
[[0.         0.17139477]
 [0.17139477 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 0 0 0 1 1 1 1]
[[-1.65659094  5.94255781 15.54967308  5.91408253  8.92460823  2.46326327
   3.41988778 11.26075935 -3.29819751 12.2820406   1.72411907  1.71535981
   8.06536961 -5.05937147  4.94476223]
 [11.69072533  6.88707924 -2.85778165  8.18871403 -0.12229528  6.9533987
  -1.77677894  6.47625017 10.52002335  6.2911272  12.17080212  4.83419657
  -2.81306314 11.61055946 -1.12018418]]
[[0.         0.88621957]
 [0.88621957 0.        ]]
Skipped small class cz.fi.muni.pa165.project.facade.StewardFacadeImpl, number of methods 9
Skipped small class cz.fi.muni.pa165.project.service.UserServiceImpl, number of methods 6
Skipped small class cz.fi.muni.pa165.project.service.BeanMappingServiceImpl, number of methods 3


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 1 1 1 1 1]
[[ 2.44048786  6.34467125  7.25937557  2.91870952  0.13883452  8.50594902
   3.56216145  2.51402879  4.44132423  2.52544451  1.98365474  7.34989023
   6.07071066  9.93780899  0.53252512]
 [ 4.80498362  4.32244015  6.46813011  1.33064985  2.49386954  8.7686615
   4.17454004  4.48242044  0.74810743  2.84218431  2.83046985  8.62632847
   7.95822001  8.35685253 -1.40597832]]
[[0.         0.05699221]
 [0.05699221 0.        ]]
Skipped small class cz.fi.muni.pa165.project.service.AirplaneServiceImpl, number of methods 8
Skipped small class cz.fi.muni.pa165.project.facade.UserFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.esports.service.CompetitionServiceImpl, number of methods 7


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0]
[[ 2.07572198 -0.1033337   9.05924988  6.6372695   3.33534551 11.21223259
   6.30297518  2.26688194  0.02044196  4.39098501 -0.79925925 -1.87605381
  -0.22061415 13.85663605  5.6659584 ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0]
[[ 1.0299902   0.34601623  5.11155653 -1.34280765  7.37195301  3.58020759
   3.99427867  4.89609146 -0.67007637 -3.16121674  4.90152311 -1.71931946
  -1.62981546  1.7604779   4.03633022]]
Skipped small class cz.muni.fi.pa165.esports.service.facade.MatchRecordFacadeImpl, number of methods 7


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 1 1 1 0 0 0 0 0]
[[ 4.23175097  4.3772192   6.32312155  1.59076869  0.42207313  4.80700159
   2.11531615  8.48375702  6.36952782 10.27569103  5.21599483  6.43296432
   8.12885952  4.4475646   2.46916556]
 [ 5.02319765  3.38134909  6.94851017  1.16781247 -1.07943141  5.63522577
   1.84300947  9.41546059  6.60281515 11.26821804  4.08495474  6.39851713
   6.98069     5.0207386   1.47300553]]
[[0.         0.01058116]
 [0.01058116 0.        ]]
Skipped small class cz.muni.fi.pa165.esports.service.config.ServiceConfiguration, number of methods 2
Skipped small class cz.muni.fi.pa165.esports.service.facade.CompetitionFacadeImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.esports.service.PlayerServiceImpl, number of methods 8
Skipped small class cz.muni.fi.pa165.esports.service.dozer.TeamStringConverter, number of methods 2
Skipped small class cz.muni.fi.pa165.esports.service.UserServiceImpl, number of methods 8


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 1 1 1 0 0 0 0 0]
[[ 4.23175097  4.3772192   6.32312155  1.59076869  0.42207313  4.80700159
   2.11531615  8.48375702  6.36952782 10.27569103  5.21599483  6.43296432
   8.12885952  4.4475646   2.46916556]
 [ 5.02319765  3.38134909  6.94851017  1.16781247 -1.07943141  5.63522577
   1.84300947  9.41546059  6.60281515 11.26821804  4.08495474  6.39851713
   6.98069     5.0207386   1.47300553]]
[[0.         0.01058116]
 [0.01058116 0.        ]]
Skipped small class cz.muni.fi.pa165.esports.service.UserService, number of methods 8
Skipped small class cz.muni.fi.pa165.esports.service.facade.UserFacadeImpl, number of methods 8
Skipped small class cz.muni.fi.pa165.esports.service.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.pa165.esports.service.facade.PlayerFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.MovieRatingServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.facade.MovieFacadeImpl, number of met

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[ 1.24602211  2.05504584  3.73633337  3.32658362 10.20923138  6.18334436
   6.92503691  6.96937752  7.76399565  8.43574715  2.48648477  1.47731698
   3.46967316 -3.64775181  5.52097511]]
Skipped small class cz.muni.fi.pa165.icehockeymanager.facades.LeagueManagerFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.Argon2ServiceImpl, number of methods 2
Skipped small class cz.muni.fi.pa165.icehockeymanager.facades.UserAuthFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.GameServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.PlayerServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.facades.UserFacadeImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.BeanMappingServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.UserAut

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 2 2 2 0 2 0 2 1 1 3 1 3 1 3 1 3]
[[ 6.11721754e+00  7.55321312e+00  1.50718772e+00  1.26205578e+01
   2.86876225e+00  2.36285455e-03  2.40419769e+00  1.49420309e+00
   2.17147875e+00  4.09374475e+00  7.00755215e+00  3.79311347e+00
   2.81048489e+00  4.91101742e+00  8.97433221e-01]
 [ 3.06038111e-01  5.96658516e+00  1.04124336e+01  7.99328470e+00
   2.79241157e+00  4.18809557e+00 -1.23863959e+00  4.65574932e+00
   7.47175121e+00  5.88850403e+00  6.57694483e+00  8.51288795e+00
   8.79320812e+00 -1.79007769e+00  3.02581167e+00]
 [ 2.90424681e+00  5.95819521e+00  6.18982017e-01  2.47494268e+00
   4.07727152e-01  1.04741440e+01  4.18409014e+00  5.20698845e-01
   8.58062744e+00 -2.21633220e+00  6.04824066e+00  8.77309227e+00
   5.98376465e+00  1.94086683e+00 -2.72532082e+00]
 [ 3.39587140e+00  8.82436085e+00 -6.40867352e-01  3.55320120e+00
   5.17023861e-01  9.39286995e+00  4.16998720e+00  4.51569468e-01
   8.70399857e+00 -3.46981692e+00  5.97104263e+00  9.13378906e+00
   4.04000282e+

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0]
[[-0.70767021  4.76587534  6.45724344 -2.4613297  11.98004055  4.32514334
   3.18311954  4.86481237 -4.06837082 -1.09149051  8.00605011 10.86425877
  -4.18390512  1.93080175  3.86294293]
 [ 5.99228716  1.0056988  -0.94749129  7.31001902  4.83361197  3.63465214
   4.01511574  9.63509274  2.34027195  2.61946535  0.79555702  2.11225748
   3.73369718  6.9193058  -3.97163749]]
[[0.         0.73306072]
 [0.73306072 0.        ]]
Skipped small class cz.muni.fi.pa165.facade.CountryFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.AssignmentServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.facade.MissionFacadeImpl, number of methods 8
Skipped small class cz.muni.fi.pa165.service.AuthenticationServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.facade.AgentFacadeImpl, number of methods 8
Skipped small class cz.muni.fi.pa165.service.MissionServiceImpl, number of methods 6
Skipped small class cz.mun

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[ 1.24602211  2.05504584  3.73633337  3.32658362 10.20923138  6.18334436
   6.92503691  6.96937752  7.76399565  8.43574715  2.48648477  1.47731698
   3.46967316 -3.64775181  5.52097511]]
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.Argon2ServiceImpl, number of methods 2
Skipped small class cz.muni.fi.pa165.icehockeymanager.facades.LeagueManagerFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.GameServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.facades.UserAuthFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.PlayerServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.facades.UserFacadeImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.BeanMappingServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.icehockeymanager.services.UserAut

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 1 1 1 1]
[[ 8.70644855  6.93112612 10.37812328 -2.96700788 -5.89192963  5.18797731
  12.22551441  2.56978583  6.08010483  7.34622002  5.03868914  6.54559708
   0.0753578   7.99128914  0.74300337]
 [ 9.42309189 12.30634785  2.58040619  8.52667618 -3.88266969  0.37689298
   2.28129601  5.34432459  7.7020483   9.84764099  7.06078291  8.37697029
   4.94535303  3.30597806  7.25195646]]
[[0.         0.32507332]
 [0.32507332 0.        ]]
Skipped small class cz.muni.fi.pa165.mvc.controllers.UserController, number of methods 8
Skipped small class cz.muni.fi.pa165.mvc.controllers.LoginController, number of methods 3
Skipped small class cz.muni.fi.pa165.mvc.controllers.HarvestController, number of methods 6
Skipped small class cz.muni.fi.pa165.mvc.controllers.AdminController, number of methods 1
Skipped small class cz.muni.fi.pa165.mvc.controllers.FeedbackController, number of methods 4
Skipped small class cz.muni.fi.pa165.mvc.controllers.RootController, number of methods 2


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[1 0 1 1 1 1 1 0 0 0 0 0 2 2 2]
[[ 9.5287323   1.88256109  8.95831966  1.27179027  1.66461432  8.8755703
   5.13784885 11.07168007 10.33973312  4.82172728  4.77222681  4.44994545
   3.99927354  8.7972765  11.4550848 ]
 [ 1.73496592 -3.00578213 12.16596127  9.84636593 -4.72242737 11.02177238
  11.83145237  5.24209785 15.37651539  3.5825665   3.00466013  3.53530478
   5.33517933 -2.04212642  4.13816404]
 [ 2.07930565 -3.17887235 13.51052666  9.55650711 -5.41961861 11.41150856
  12.83890724  4.15832233 16.22310829  4.00639343  4.12679148  3.3080039
   5.89417982 -1.74054921  4.34639883]]
[[0.         0.29229323 0.29437089]
 [0.29229323 0.         0.00244022]
 [0.29437089 0.00244022 0.        ]]
Skipped small class cz.muni.fi.timeline.mapper.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.timeline.service.TimelineCommentServiceImpl, number of methods 5


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[2 3 0 1 3 3 3 2 0 1 3 2 3 0 1]
[[ 7.84641027  7.63311005  0.77862138  3.49440241  9.12470531  5.60199738
   5.80630016  3.95609665  1.17287362  1.72045743  0.64830434  3.61434293
   6.70607615 11.55066872  4.75529289]
 [ 5.84349442  9.44514847  2.89768457  0.99020791  6.37031174  4.84804106
   3.45792079  8.64195442 -1.01368451 -0.59512126  1.97943175  7.32799053
   7.83668852  9.56758022  3.73515821]
 [ 5.7931881   9.49673653  1.56725454  2.13082242  5.44557476  3.69976211
   4.76186037  7.86004972  0.33725849  1.4774543  -0.0222958   6.69947433
   9.69715405  8.05711651  2.41473603]
 [ 5.90201044  9.45636272  1.90874624  1.82111287  6.87373114  3.89845943
   4.18135357  7.31204319  0.02538905  1.02751303  0.81741899  6.0211668
   8.60293388  8.95917988  2.80444932]]
[[0.         0.08354956 0.08120665 0.05463047]
 [0.08354956 0.         0.0253292  0.01304157]
 [0.08120665 0.0253292  0.         0.00700629]
 [0.05463047 0.01304157 0.00700629 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 0 0 1 1 0 1 1 1]
[[ 3.0352459   6.27983761  9.5659008   5.69615221  1.62468863  9.86991024
   4.96523428  7.50336981  3.36961865  5.29161501  0.32773703  3.73192739
   5.76185513  4.16595745 -0.54637992]
 [ 0.17278136  1.44424701  6.78280401  6.92853212  2.20244598  7.89588928
   3.14097452  7.48198843  3.37744689  2.57932568  2.71246099  7.04436111
   5.24532652  7.86168528  5.04286957]]
[[0.         0.13324686]
 [0.13324686 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 1 1 1 0 1 1 1 0 0]
[[ 5.26160479  6.76227045  1.00216413  4.24149847  8.91499901  6.00308561
  -0.51907158  3.22843099  4.45188808  3.69374776 -1.54232943  3.79465604
   0.07519867  6.27599525  7.35656834]
 [ 6.72969961  6.68215704  4.41174793  7.59823132  8.56694317  3.9018662
   0.33737674  2.3250351   4.69986868  3.06927109 -0.00995924  5.95154953
   1.42536914  6.14361525  3.11571193]]
[[0.         0.07873957]
 [0.07873957 0.        ]]
Skipped small class cz.muni.fi.timeline.service.StudyGroupServiceImpl, number of methods 7
Skipped small class cz.muni.fi.timeline.facade.StudyGroupFacadeImpl, number of methods 8
Skipped small class cz.muni.fi.timeline.service.HistoricalTimelineServiceImpl, number of methods 6
Skipped small class cz.muni.fi.timeline.service.HistoricalEventServiceImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.sampledata.SampleDataLoadingFacadeImpl, number of methods 1
Skipped small class cz.muni.fi.pa165.mvc.controllers.MovieController, numbe

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[1 1 1 0 2 2 1 0 0 0 0 0 0 2 2 1 1 0]
[[14.47014427  5.82075787  5.523736   -6.29363775  4.03529787 -1.68220675
   9.81716633  9.79262257  5.0142622  12.25300694  5.49523878 10.11027431
   8.1534481   3.71855545  1.79123378]
 [ 4.36904097  8.29364491  9.51407337  4.79743814  4.41552544  4.59539318
   4.51561356  9.90945053  7.12517023  3.51297879  4.75574255  7.8872757
   7.55040598  4.22236061  3.72808528]
 [ 3.6778357   8.11594391  8.55110168  5.53154087  3.96085596  4.25525904
   4.98557997  9.92683792  7.02734947  4.50904846  5.59776926  7.76623869
   8.51046658  4.04946995  2.7431767 ]]
[[0.         0.25113919 0.24743814]
 [0.25113919 0.         0.00515848]
 [0.24743814 0.00515848 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0]
[[5.68600082 3.38646126 9.34127235 1.80446935 2.41927528 7.89854574
  0.81323016 7.10027695 6.25208378 7.32637739 6.88919878 4.57482719
  6.21082449 6.28646755 6.46265936]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 1 1 1 0 0]
[[ 3.32737756  5.30852175  7.15675926  1.04357469 -0.67473984  3.62971401
   9.77044201  1.09928429  8.79682922  5.61633062  6.00159216  0.47523099
   2.52560949  8.91433525  4.82280684]
 [ 2.03179336  5.98614407  6.306458    0.65189028  0.38353276  3.91405869
   9.80628109  1.90103769  9.55045414  6.20632362  7.38985014 -0.22911611
   2.97817922  9.07299995  6.3344121 ]]
[[0.         0.00947515]
 [0.00947515 0.        ]]
Skipped small class cz.fi.muni.pa165.service.facade.StatisticsFacadeImpl, number of methods 1


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1]
[[ 8.45780182  0.60341072  0.71381521  3.35498691  2.69612718  3.12678051
   6.96098518 -0.3200874   2.06157732  6.27223015  5.88767147  3.15514445
   2.04350138  6.2644968  -2.13462591]
 [ 7.24651766  2.06442785 -0.52663726  4.75275707  1.71261692  3.63745761
   9.06874943  0.21323188  3.44985127  4.83571434  5.6288681   3.1099894
   1.53643656  6.88157606 -1.26317036]]
[[0.         0.03070018]
 [0.03070018 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 1 0 1 1 0 2 2 0 2]
[[6.7415576  4.77454138 4.70812798 8.21204567 2.70611358 6.50663614
  9.41687679 8.83113003 2.52662563 5.17399168 6.81016016 5.05490923
  5.17456007 5.89274359 6.59265947]
 [7.78073215 5.39371538 4.05086565 8.13810825 2.55754566 6.68753624
  9.13620377 8.33996773 2.79973912 5.39714909 7.12936974 6.25472069
  5.69248867 4.71323633 6.36732721]
 [7.7661643  5.5314436  3.73310232 7.87751675 2.34782267 6.85050488
  8.55381966 8.22544861 3.59913349 5.72227669 7.79877377 6.50998592
  5.86896896 4.36552429 5.98850727]]
[[0.         0.00470401 0.00987964]
 [0.00470401 0.         0.0018081 ]
 [0.00987964 0.0018081  0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[ 4.00803614  2.69901466  4.54062939  6.07139206  2.7141118  11.58889484
   3.76147532  3.35266066  3.02101326  0.16068654  7.90956688  6.14926243
   3.31147146  7.33683538  3.99203825]]
Skipped small class cz.fi.muni.pa165.service.serviceImpl.AddressServiceImpl, number of methods 2
Skipped small class cz.fi.muni.pa165.service.facade.MeterLogFacadeImpl, number of methods 6


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 1 1 1 1 0]
[[ 8.94688511  5.13187933  7.00824833  5.44888973 -0.7881425   6.10087919
   2.66297007  0.76541442  6.06064987  3.71248293  5.14843988  5.46541405
   5.31105566  3.85043359  2.45431089]
 [ 9.29026222  7.68439484  4.97461557  2.84284973  1.971982    6.92980957
   1.94537437  3.15209341  6.51034975  2.90799212  8.17519093  6.60058403
   8.05881023  5.57869577  4.82306242]]
[[0.         0.05446825]
 [0.05446825 0.        ]]
Skipped small class cz.muni.fi.pa165.data.DataLoadUtil, number of methods 1
Skipped small class cz.fi.muni.pa165.yellow_yak.service.CompetitionServiceImpl, number of methods 6
Skipped small class cz.fi.muni.pa165.yellow_yak.facade.TeamFacadeImpl, number of methods 4
Skipped small class cz.fi.muni.pa165.yellow_yak.service.TeamServiceImpl, number of methods 5
Skipped small class cz.fi.muni.pa165.yellow_yak.facade.ScoreFacadeImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.yellow_yak.service.GameServiceImpl, number of methods 5
Ski

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 1 1 1 1 1 0]
[[11.57550812 -0.29464382  0.50661761  2.80735135  7.31638384  5.76129675
  -0.29275116  0.46225137  8.78835201  8.30671692 -0.02413008  6.66950893
  -0.77443737  1.13450277 -4.1846385 ]
 [ 6.02060318  8.45072079  3.61865377 -3.73073936  3.0331192   3.15508986
   3.50031686  6.11778784  4.04164457  3.81173444  4.01800871  1.62480068
   4.75787163  6.96134186  4.21759129]]
[[0.         0.57380142]
 [0.57380142 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[1 1 1 2 2 2 2 1 0 0 0]
[[ 5.77411747  6.28287029  9.78492069  6.88372231  2.5608933   0.40773773
   3.87857175  8.79177094  1.23263812  9.07938957  2.48635554 11.01198483
   6.16865301  6.63922882  3.02477288]
 [ 4.12029266  5.86421776  9.77962494  6.49418926  3.21343136 -0.24782862
   2.74119973  7.27182913  1.74900198  8.06562996  1.63495743 11.20571327
   6.79445362  7.63493061  1.55309594]
 [ 5.26756859  6.88240528  9.68117714  6.82704306  3.05169368  0.02469529
   3.25382113  8.23376369  1.44803107  8.83918571  2.52304006 10.42175388
   6.67846107  7.26738644  2.12978816]]
[[0.         0.01006151 0.00287757]
 [0.01006151 0.         0.00493863]
 [0.00287757 0.00493863 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0]
[[12.14743042  8.4563303   1.38948298  0.22392647 -0.32589021  1.50408912
  -0.4307408   9.38534451  2.62946033  5.4216671   3.07065296  5.3041172
   0.20145673  3.59316444 -1.20150936]]
Skipped small class cz.muni.fi.pa165.facade.TimelineFacadeImpl, number of methods 9


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 1 1 1 1 1 1 1]
[[6.892344   1.7916038  1.56180072 4.2075386  5.94522285 3.58725977
  5.39404154 4.49179459 3.88841271 4.66353989 6.0547452  1.89233351
  3.67133689 5.45980787 3.47726727]
 [7.4409256  2.62343979 2.89389396 3.01531315 4.35357809 4.15779495
  6.2587266  3.02712846 4.68423653 4.94113684 4.98305321 1.32470131
  3.51354599 5.51532221 5.1675992 ]]
[[0.        0.0246557]
 [0.0246557 0.       ]]
Skipped small class cz.muni.fi.pa165.service.BeanMappingServiceImpl, number of methods 3


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 1 0 0 1 1 1 1 0 1 1]
[[ 8.39051437  2.11222816  1.53462458  3.32552218  4.54095697  8.32004547
  -1.08777571  3.50135899  9.0708828   2.32801414  2.35007596  1.63635421
   9.72928333 10.68129158  8.08078289]
 [ 7.66552114  3.41222644  2.36868453  2.97783995  6.10369682  4.53757095
   5.49256849  7.26851845  5.41918612  3.35544109  1.19694006  3.99356365
   4.81634903  6.69814444  7.53569889]]
[[0.         0.13228052]
 [0.13228052 0.        ]]
Skipped small class cz.muni.fi.pa165.service.StudyGroupServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.service.CommentServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.facade.StudyGroupFacadeImpl, number of methods 4
Skipped small class cz.muni.fi.pa165.rest.hateoas.GenreRepresentationModelAssembler, number of methods 1
Skipped small class cz.muni.fi.pa165.rest.hateoas.UserRepresentationModelAssembler, number of methods 1
Skipped small class cz.muni.fi.pa165.rest.hateoas.MovieListRepresentationModelAs

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 1 1 1 1 1 0 1 1 0 0 0]
[[ 5.52734041  3.39867043  5.15204477  1.3134836   6.45898294  4.07482815
   6.25813961 13.4419241  15.65309525  7.34193611  6.00066853  1.73228049
   7.16499901  1.0623579   1.75178802]
 [-1.16768694  5.73319769  2.02933335 -0.06497583  2.85376549  7.83974504
   9.67997169  3.50601864 -2.09064293 -2.48656845 -1.20738673 10.25783062
   7.70608997  3.14239216  8.56866646]]
[[0.         0.63810946]
 [0.63810946 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0]
[[ 6.2444067  -1.96345723  6.14069653  7.38219833 -0.75473368  6.31469154
  -0.46152753  7.14985943  4.46791792 -0.73421174  3.98383665 10.93210793
   2.03658128  4.61100054  7.97549677]]
Skipped small class tennisclub.facade.CourtFacadeImpl, number of methods 8


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 1 0 1 0 1 1 1 1 1]
[[ 2.08037376  2.06360483  5.89808941  9.64089584  3.13288808  5.06007576
   1.70602453  2.98940921  3.93290496  8.48139572  3.69091201  4.47540855
  -0.34069207  2.64344573 -0.75827783]
 [-0.41043019  6.23845482  3.01931357  8.49323654 -0.44026211 10.60338497
   3.49334836  6.9671607   6.81155348  4.07041645  6.7394371   8.05756092
   3.0658803   4.82092667 -0.98827362]]
[[0.        0.1769079]
 [0.1769079 0.       ]]
Skipped small class tennisclub.service.EventServiceImpl, number of methods 6
Skipped small class tennisclub.service.TimeServiceImpl, number of methods 4


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1]
[[ 2.91042066 13.28315449  5.32437038  4.67475796 -5.45818901  8.67996883
   6.6490283   2.4480803   5.20922947  6.18863201 -1.04905164 11.11548138
   2.12526608  3.20469546  5.70166636]
 [ 9.60044575  5.00841379 15.47548199  3.61010408  1.97080815  5.69843674
  13.16939354 14.28450394 17.23217964  5.81838846  7.09050608 -1.30098069
   3.82483625  1.24147892 -0.63384509]]
[[0.         0.45770685]
 [0.45770685 0.        ]]
Skipped small class tennisclub.service.BookingService, number of methods 9
Skipped small class tennisclub.service.EventService, number of methods 6
Skipped small class tennisclub.facade.BookingFacadeImpl, number of methods 9


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 1 1 1 1 1 0 1 1 0 0 0]
[[ 5.52734041  3.39867043  5.15204477  1.3134836   6.45898294  4.07482815
   6.25813961 13.4419241  15.65309525  7.34193611  6.00066853  1.73228049
   7.16499901  1.0623579   1.75178802]
 [-1.16768694  5.73319769  2.02933335 -0.06497583  2.85376549  7.83974504
   9.67997169  3.50601864 -2.09064293 -2.48656845 -1.20738673 10.25783062
   7.70608997  3.14239216  8.56866646]]
[[0.         0.63810946]
 [0.63810946 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0]
[[-2.10613513 -2.46940351 10.15216827  5.48604393  1.56925309 -0.53299367
  -2.52894306  5.91905499 10.70881557  5.38167858  9.34383774 10.89305019
   7.32552433  8.21423054  1.10534358]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[10.89481163  2.67216516  2.21863842  1.37028742  5.90928793  7.09170246
   4.94273281  2.47429681  6.86044979  4.94773483  5.70307255  2.97058296
   3.08129859  4.63871145  0.93091822]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[10.89481163  2.67216516  2.21863842  1.37028742  5.90928793  7.09170246
   4.94273281  2.47429681  6.86044979  4.94773483  5.70307255  2.97058296
   3.08129859  4.63871145  0.93091822]]
Skipped small class tennisclub.facade.EventFacadeImpl, number of methods 6
Skipped small class tennisclub.service.BookingServiceImpl, number of methods 9
Skipped small class tennisclub.service.JWTService, number of methods 2
Skipped small class tennisclub.facade.UserFacadeImpl, number of methods 9
Skipped small class tennisclub.service.TimeService, number of methods 4
Skipped small class cz.muni.fi.pa165.service.facade.ImageFacadeImpl, number of methods 1


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[ 1.85215795  5.22887945  5.14260626  8.29380894  7.23048353  9.27448463
   6.50196362  6.33898163  5.73436213 -0.30328295  4.962708    3.08848524
   2.3057673   3.79047608  5.33277512]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[2.2476449  6.38168383 8.11250687 5.63790607 6.21589661 6.34284401
  3.04200745 9.42457867 2.56099796 4.10308695 7.39197445 5.21230745
  3.65659499 3.51925206 2.01552892]]
Skipped small class cz.muni.fi.pa165.service.UserServiceImpl, number of methods 9
Skipped small class cz.muni.fi.pa165.service.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.pa165.service.ImageServiceImpl, number of methods 4
Skipped small class cz.muni.fi.pa165.service.facade.UserRatingFacadeImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.service.PersonServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.service.GenreServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.facade.GenreFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.UserRatingServiceImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.service.facade.PersonFacadeImpl, number of methods 6
Skipped small c

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0]
[[10.46932507  5.60064602  7.05717373  1.57758045  3.36109614  7.22296572
   2.30961466 11.15492058  6.4495182   7.78327417  1.7204082   1.31009126
   3.27859282  1.26345861  2.59923053]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0]
[[ 2.19717813  7.62469196  8.21844959  4.33793736  7.60888052 -3.08774137
  -1.38449335  7.41358995  7.25931835  6.14200735  2.46462107  7.46182346
  -2.4711628  11.50399876  4.22113562]]
Skipped small class cz.muni.fi.pa165.service.UserServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.service.UserService, number of methods 6
Skipped small class cz.muni.fi.pa165.service.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.fi.muni.pa165.hockeymanager.mvc.formatters.IdToTeamConverter, number of methods 1
Skipped small class cz.fi.muni.pa165.hockeymanager.mvc.controllers.MatchController, number of methods 5
Skipped small class cz.fi.muni.pa165.hockeymanager.mvc.controllers.UserController, number of methods 3
Skipped small class cz.fi.muni.pa165.hockeymanager.mvc.controllers.LoginController, number of methods 3
Skipped small class cz.fi.muni.pa165.hockeymanager.mvc.controllers.HockeyPlayerController, number of methods 8


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[7.21244669 9.64386463 6.52562952 5.23760605 5.33814955 6.10905027
  2.98118615 8.26733875 3.87418127 8.1142416  1.12824714 7.05640268
  5.30317116 7.46016455 3.63679647]]
Skipped small class cz.fi.muni.pa165.yellow_yak.sampledata.SampleDataLoadingFacadeImpl, number of methods 1
Skipped small class cz.muni.pa165.teamwhite.formula1.rest.security.UserDetailsServiceImpl, number of methods 1
Skipped small class cz.muni.pa165.teamwhite.formula1.rest.security.JwtUtils, number of methods 3
Skipped small class cz.muni.pa165.teamwhite.formula1.rest.security.AuthEntryPointJwt, number of methods 2
Skipped small class cz.fi.muni.pa165.service.service.song.SongServiceImpl, number of methods 6
Skipped small class cz.fi.muni.pa165.service.facade.ConcertFacadeImpl, number of methods 6
Skipped small class cz.fi.muni.pa165.service.service.band.BandServiceImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.service.tour.TourServiceImpl, number of methods 6
Skipp

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0]
[[5.38553667 6.68345356 4.06289768 9.77902889 7.25637293 4.76264572
  5.62618446 7.10513449 4.35263729 7.57437515 3.83991838 3.42004991
  2.96165419 5.28491449 1.15516698]]
Skipped small class cz.fi.muni.pa165.service.service.presentation.PresentationDataServiceImpl, number of methods 1
Skipped small class cz.fi.muni.pa165.service.facade.SongFacadeImpl, number of methods 6


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[-0.852687   10.01964092  2.78133988  1.85698891  0.94295084  6.00039625
   4.23511648  8.48824692 -0.34684032  8.6668663   4.35326862  3.48070955
   0.94205713  5.14144945  9.7473793 ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0]
[[-1.16371     5.91244555  5.65475559  5.59149933  2.12588859  5.45850277
   5.64842367  7.93063164  5.64788818  4.46838093  3.92796826  6.01622772
  -2.93620944  6.47346306  1.35285318]]
Skipped small class cz.fi.muni.pa165.service.facade.TourFacadeImpl, number of methods 6
Skipped small class cz.fi.muni.pa165.service.facade.BandFacadeImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.facade.PresentationDataFacadeImpl, number of methods 1
Skipped small class cz.fi.muni.pa165.service.facade.AlbumFacadeImpl, number of methods 6


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[ 2.18683815  4.98331499  6.26615095 -1.13197517  2.91705394  4.23741007
   9.77380848  9.42451286  5.99503469  5.55255651 -0.3573899   7.02768946
  -1.1009264   4.63781071  4.18570375]]
Skipped small class cz.muni.fi.timeline.data.TimelineDataLoaderImpl, number of methods 1
Skipped small class cz.muni.fi.pa165.sampledata.SampleDataLoadingFacadeImpl, number of methods 1
Skipped small class cz.muni.fi.services.impl.ComponentServiceImpl, number of methods 5
Skipped small class cz.muni.fi.services.config.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.facades.RocketFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.services.impl.MissionServiceImpl, number of methods 7
Skipped small class cz.muni.fi.facades.MissionFacadeImpl, number of methods 7
Skipped small class cz.muni.fi.services.impl.RocketServiceImpl, number of methods 5


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[-0.71754318  2.76002502 10.00439548  3.82754636 -1.20938921 -1.90517664
   4.60800457  8.66725826 -3.02993202  1.416381    7.71182251  5.02596092
   8.78643513  9.16143131  6.23970366]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[11.93323517  7.10533714  4.00955629  1.11855245  7.05699587  4.09151983
  12.58237648  2.420506    3.94583988  3.55614352  2.56236625  2.99127865
   0.11795913  5.21785498 -2.26193762]]
Skipped small class cz.muni.fi.facades.ComponentFacadeImpl, number of methods 5
Skipped small class cz.fi.muni.pa165.service.mapping.mapstruct.MusicianMapperImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.mapping.mapstruct.ConcertMapperImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.mapping.mapstruct.SongMapperImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.mapping.mapstruct.TourMapperImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.mapping.mapstruct.AlbumMapperImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.mapping.mapstruct.BandMapperImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.service.mapping.mapstruct.ManagerMapperImpl, number of methods 7
Skip

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0]
[[-0.8124131   5.1321764   3.99606156  6.34784794  8.29877663  3.44012308
   2.69764996  5.70163107  4.81247377  2.14921761  4.4585042   4.69047976
   5.29871178  6.92351484  5.60675287]]
Skipped small class cz.fi.muni.pa165.hockeymanager.service.facade.UserFacadeImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.hockeymanager.service.HockeyPlayerServiceImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.hockeymanager.service.facade.HockeyPlayerFacadeImpl, number of methods 6
Skipped small class cz.fi.muni.pa165.hockeymanager.service.UserServiceImpl, number of methods 7
Skipped small class cz.fi.muni.pa165.hockeymanager.service.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.fi.muni.pa165.hockeymanager.service.MatchServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.mvc.controllers.CommentController, number of methods 4
Skipped small class cz.muni.fi.pa165.mvc.controllers.EventController, number of meth

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 1 1 0 1 1 1 1 1 0 0 0 1]
[[ 7.66458988  5.24015808 -0.72423828 -2.4935832   6.76643515  5.70148849
   5.55052948  6.09639025  6.41234589  0.27916777  3.2147131   6.09653997
   0.01783009  2.72689414  7.60482597]
 [10.38587952  3.37148929  2.72885513 -0.87829596  6.26868677  6.61744833
   5.38271427  4.61959314  6.3428607   3.41392589  5.62161875  2.64268684
   1.95733047  5.19951344  4.13728237]]
[[0.         0.09862326]
 [0.09862326 0.        ]]


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[ 6.70501328  6.1499548   2.76138353  5.61149645  3.23344684  6.70608187
   5.62093115  2.07180905  1.4613812   6.32469797  3.07822633 -1.11155748
   4.9919486   4.65274477  5.0173645 ]]
Skipped small class cz.muni.fi.pa165.service.UserServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.UserService, number of methods 5
Skipped small class cz.muni.fi.pa165.service.facade.ReviewFacadeImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.service.BeanMappingServiceImpl, number of methods 3
Skipped small class cz.muni.fi.pa165.service.facade.GenreFacadeImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.GenreServiceImpl, number of methods 5
Skipped small class cz.muni.fi.pa165.service.facade.UserFacadeImpl, number of methods 5
Skipped small class sportsclub.service.AgeGroupServiceImpl, number of methods 0
Skipped small class sportsclub.service.TeamServiceImpl, number of methods 3
Skipped small class sport

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[ 0  0 -1  0 -1 -1 -1 -1 -1 -1]
[[-0.37380758  1.72241318  5.16995859  4.23090935  9.47645473  1.45665872
   4.69809675  2.35781574  5.84106588  1.90402079  7.18458652  8.6033783
   8.01533985  2.48858619  7.01929617]]
Skipped small class sportsclub.facade.impl.AgeGroupFacadeImpl, number of methods 2
Skipped small class sportsclub.facade.impl.PlayerFacadeImpl, number of methods 4
Skipped small class cz.muni.fi.pa165.service.impl.ScoreComputationServiceImpl, number of methods 7


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[6.67411947 3.99454761 6.24233389 4.40876913 4.25476503 4.04291582
  2.34772086 8.97200871 8.23181629 3.16628265 6.78442621 2.85012245
  3.2918005  4.604743   5.99258518]]
Skipped small class cz.muni.fi.pa165.service.impl.RecommendationServiceImpl, number of methods 2
Skipped small class cz.muni.fi.pa165.facade.RatingFacadeImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.service.impl.MovieServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.facade.PersonFacadeImpl, number of methods 7


/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


[0 0 0 0 0 0 0 0 0 0]
[[6.5861721  1.59521413 4.08331299 7.82051849 2.52133083 0.39316919
  2.70825601 2.46203732 2.84131718 5.47133541 4.12292147 6.94281769
  8.21048641 3.77134347 5.39364529]]
[0 0 0 0 0 0 0 0 0 0]
[[5.63911533 4.71549416 7.33230734 4.0613308  3.47320795 9.74723148
  2.98331451 9.99026299 2.2261436  6.82679367 5.85343361 2.26238751
  2.79037642 5.87942648 3.38563418]]
Skipped small class cz.muni.fi.pa165.service.impl.PersonServiceImpl, number of methods 6
Skipped small class cz.muni.fi.pa165.service.impl.RatingServiceImpl, number of methods 7
Skipped small class cz.muni.fi.pa165.sampledata.SampleDataLoadingFacadeImpl, number of methods 1
Skipped small class cz.muni.pa165.teamwhite.formula1.service.CarServiceImpl, number of methods 5
Skipped small class cz.muni.pa165.teamwhite.formula1.service.DriverServiceImpl, number of methods 5
Skipped small class cz.muni.pa165.teamwhite.formula1.service.facade.DriverFacadeImpl, number of methods 6
Skipped small class cz.muni.pa16

/home/martin/Projects/Master's Thesis/JENA/JENA.V2/.venv/lib/python3.13/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


In [15]:
import pandas as pd

# input_file = "/media/martin/BigData/datasets/github-projects/klaw/multi-service-final-multiply_signature-remove-words_yes.jsonl"
input_file = (
    "/media/martin/BigData/datasets/github-projects/klaw/final-with-centroids.jsonl"
)
input_file = (
    "/media/martin/BigData/datasets/pa165-git/multi-service-with-distances.jsonl"
)
# input_file = "/media/martin/BigData/datasets/github-projects/cas/multi-service-result-codebert-combined.jsonl"

df = pd.read_json(input_file, lines=True)
df = df.query("optimal_k.notnull()")
more_cluster_lines = df.query("optimal_k > 2")
one_cluster_lines = df.drop(more_cluster_lines.index)


def count_rows_and_print(df: pd.DataFrame, query: str, stat_type: str):
    df_part = df.query(query)
    count = len(df_part)
    print(f"{stat_type}: {count}")
    for _, record in df_part.iterrows():
        print(record["fullyQualifiedName"])
        # print(json.dumps(record["methods"], indent=2))
    print("---")
    return count


false_negatives = count_rows_and_print(
    one_cluster_lines, "label == 1", "False negatives"
)
true_negatives = count_rows_and_print(one_cluster_lines, "label == 0", "True negatives")
false_positives = count_rows_and_print(
    more_cluster_lines, "label == 0", "False positives"
)
true_positives = count_rows_and_print(
    more_cluster_lines, "label == 1", "True positives"
)

precision = true_positives / (true_positives + false_positives)
recall = true_positives / (true_positives + false_negatives)
accuracy = (true_positives + true_negatives) / (
    true_positives + false_positives + false_negatives + true_negatives
)
f1_score = 2 * ((precision * recall) / (precision + recall))

print(f"""
Stats
Precision: {precision}
Recall: {recall}
Accuracy: {accuracy}
F1 score: {f1_score}
-------------
""")

# eval_df = df[df["label"].notna()]
# y_true = eval_df["label"].astype(int)
# y_pred = pd.Series(0, index=eval_df.index)
# y_pred[eval_df.index.isin(more_cluster_lines.index)] = 1

# print("Stats")
# print(classification_report(y_true, y_pred, target_names=["Cohesive", "Multiservice"]))

# class_clusters = defaultdict(dict)
#
# for _, record in more_cluster_lines.iterrows():
#     k = record["optimal_k"]
#     clusters = record["cluster"]
#     methods = record["methods"]
#     class_name = record["fullyQualifiedName"]
#     cohesion = record["lcom4"]
#     noise_ratio = record["noise_ratio"]
#
#     method_clusters = {}
#     for index, cluster in enumerate(clusters):
#         cluster_number_str = str(cluster)
#         method = methods[index]
#         if cluster_number_str in method_clusters:
#             method_clusters[cluster_number_str].append(method)
#         else:
#             method_clusters[cluster_number_str] = [method]
#
#     class_clusters[class_name]["methods"] = method_clusters
#     class_clusters[class_name]["lcom4"] = cohesion
#     class_clusters[class_name]["noise_ratio"] = noise_ratio
#
# for className, metadata in class_clusters.items():
#     print(f"--- Class {className}, LCOM4: {metadata['lcom4']} ---")
#     for cluster, methods in metadata["methods"].items():
#         print(f"Cluster {cluster}: {json.dumps(methods, indent=2)}\n")
#     print()

df

False negatives: 5
cz.fi.muni.pa165.winery.service.BeanMappingServiceImpl
cz.muni.fi.pa165.airportmanager.service.AirplaneServiceImpl
cz.muni.fi.pa165.mvc.config.DataSeeder
cz.muni.fi.pa165.facade.EventFacadeImpl
cz.fi.muni.pa165.hockeymanager.mvc.controllers.TeamController
---
True negatives: 60
cz.idomatojde.services.TimetableServiceImpl
cz.muni.fi.pa165.service.BeerService
cz.muni.fi.pa165.service.facade.BeerFacadeImpl
cz.muni.fi.pa165.service.BeerServiceImpl
muni.pa165.services.UserServiceImpl
cz.fi.muni.pa165.service.OrderServiceImpl
cz.fi.muni.pa165.service.facade.WineFacadeImpl
cz.fi.muni.pa165.service.WineServiceImpl
cz.fi.muni.pa165.service.WineService
cz.fi.muni.pa165.service.UserServiceImpl
cz.fi.muni.pa165.service.UserService
cz.fi.muni.pa165.service.OrderService
cz.fi.muni.pa165.service.facade.OrderFacadeImpl
cz.fi.muni.pa165.service.facade.UserFacadeImpl
cz.fi.muni.pa165.project.service.AirportServiceImpl
cz.fi.muni.pa165.project.facade.AirportFacadeImpl
cz.fi.muni.pa165.

,methods,lcom4,fullyQualifiedName,startLine,label,optimal_k,noise_ratio,cluster,avg_dist
19,"[{'name': 'mapTo', 'signature': 'List<T> mapTo...",4,cz.fi.muni.pa165.winery.service.BeanMappingSer...,22,1,1.0,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.00000
35,"[{'name': 'find', 'signature': 'Airplane find(...",1,cz.muni.fi.pa165.airportmanager.service.Airpla...,18,1,1.0,0.181818,"[0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0]",0.00000
42,"[{'name': 'createTimetable', 'signature': 'Tim...",1,cz.idomatojde.services.TimetableServiceImpl,19,0,1.0,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.00000
45,"[{'name': 'toOfferDTO', 'signature': 'OfferDTO...",2,cz.idomatojde.services.base.MappingServiceImpl,43,1,5.0,0.000000,"[0, 0, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0, 1, 1, 1, ...",8.96476
62,"[{'name': 'create', 'signature': 'Beer create(...",-1,cz.muni.fi.pa165.service.BeerService,16,0,1.0,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.00000
...,...,...,...,...,...,...,...,...,...
430,"[{'name': 'create', 'signature': 'void create(...",1,cz.muni.fi.pa165.service.MovieServiceImpl,25,0,1.0,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.00000
451,"[{'name': 'findAll', 'signature': 'List<System...",2,sportsclub.facade.impl.AccountFacadeImpl,33,0,1.0,0.700000,"[0, 0, -1, 0, -1, -1, -1, -1, -1, -1]",0.00000
455,"[{'name': 'create', 'signature': 'MovieDetaile...",1,cz.muni.fi.pa165.facade.MovieFacadeImpl,28,0,1.0,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.00000
460,"[{'name': 'register', 'signature': 'User regis...",3,cz.muni.fi.pa165.service.impl.UserServiceImpl,24,0,1.0,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.00000


In [ ]:
from pipelines.shared import input_until_integer

# Labeling script

input_file = "/media/martin/BigData/datasets/github-projects/klaw/multi-service.jsonl"
output_file = (
    "/media/martin/BigData/datasets/github-projects/klaw/multi-service-labeled.jsonl"
)

df = read_json(input_file, lines=True)

df["label"] = pd.Series()

for index, row in df.iterrows():
    name = row["fullyQualifiedName"]
    methods = row["methods"]
    assigned_label = row["label"]
    lcom4 = row["lcom4"]

    label = 0
    if not should_be_skipped(name) and len(methods) > 10:
        print("-" * 10)
        print(f"Class {name} (LCOM4 {lcom4})")
        print("Methods: ")
        for method in methods:
            print(method)

        label = input_until_integer("Enter label: ")

    df.loc[index, "label"] = label
    df.to_json(output_file, lines=True, orient="records")

# Results

## Remove words: yes, names multiply: 1.3

```
False negatives: 1
io.aiven.klaw.service.UtilControllerService
---
True negatives: 10
io.aiven.klaw.MockMethods
io.aiven.klaw.repository.MessageSchemaRepo
io.aiven.klaw.repository.ActivityLogRepo
io.aiven.klaw.controller.AclController
io.aiven.klaw.repository.KwKafkaConnectorRepo
io.aiven.klaw.controller.TopicController
io.aiven.klaw.repository.SchemaRequestRepo
io.aiven.klaw.controller.KafkaConnectController
io.aiven.klaw.service.AnalyticsControllerService
io.aiven.klaw.service.MailUtils
---
False positives: 9
io.aiven.klaw.clusterapi.services.ConfluentCloudApiService
io.aiven.klaw.controller.SchemaRegistryController
io.aiven.klaw.repository.AclRequestsRepo
io.aiven.klaw.repository.AclRepo
io.aiven.klaw.repository.KwKafkaConnectorRequestsRepo
io.aiven.klaw.repository.TopicRequestsRepo
io.aiven.klaw.repository.RegisterInfoRepo
io.aiven.klaw.repository.TopicRepo
io.aiven.klaw.service.ClusterApiService
---
True positives: 15
io.aiven.klaw.clusterapi.utils.ClusterApiUtils
io.aiven.klaw.clusterapi.controller.ClusterApiController
io.aiven.klaw.UtilMethods
io.aiven.klaw.helpers.HandleDbRequests
io.aiven.klaw.controller.TemplateMapController
io.aiven.klaw.controller.UsersTeamsController
io.aiven.klaw.controller.EnvsClustersTenantsController
io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc
io.aiven.klaw.helpers.db.rdbms.HandleDbRequestsJdbc
io.aiven.klaw.helpers.db.rdbms.InsertDataJdbc
io.aiven.klaw.helpers.db.rdbms.DeleteDataJdbc
io.aiven.klaw.service.ServerConfigService
io.aiven.klaw.service.UsersTeamsControllerService
io.aiven.klaw.service.CommonUtilsService
io.aiven.klaw.clusterapi.UtilMethods
---

Stats
Precision: 0.625
Recall: 0.9375
Accuracy: 0.7142857142857143
F1 score: 0.75
```

## Remove words: yes, names multiply: no

```
False negatives: 2
io.aiven.klaw.clusterapi.controller.ClusterApiController
io.aiven.klaw.service.UtilControllerService
---
True negatives: 13
io.aiven.klaw.clusterapi.services.ConfluentCloudApiService
io.aiven.klaw.MockMethods
io.aiven.klaw.controller.SchemaRegistryController
io.aiven.klaw.repository.MessageSchemaRepo
io.aiven.klaw.repository.ActivityLogRepo
io.aiven.klaw.controller.AclController
io.aiven.klaw.repository.KwKafkaConnectorRepo
io.aiven.klaw.controller.TopicController
io.aiven.klaw.repository.SchemaRequestRepo
io.aiven.klaw.controller.KafkaConnectController
io.aiven.klaw.service.AnalyticsControllerService
io.aiven.klaw.service.MailUtils
io.aiven.klaw.service.ClusterApiService
---
False positives: 6
io.aiven.klaw.repository.AclRequestsRepo
io.aiven.klaw.repository.AclRepo
io.aiven.klaw.repository.KwKafkaConnectorRequestsRepo
io.aiven.klaw.repository.TopicRequestsRepo
io.aiven.klaw.repository.RegisterInfoRepo
io.aiven.klaw.repository.TopicRepo
---
True positives: 14
io.aiven.klaw.clusterapi.utils.ClusterApiUtils
io.aiven.klaw.UtilMethods
io.aiven.klaw.helpers.HandleDbRequests
io.aiven.klaw.controller.TemplateMapController
io.aiven.klaw.controller.UsersTeamsController
io.aiven.klaw.controller.EnvsClustersTenantsController
io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc
io.aiven.klaw.helpers.db.rdbms.HandleDbRequestsJdbc
io.aiven.klaw.helpers.db.rdbms.InsertDataJdbc
io.aiven.klaw.helpers.db.rdbms.DeleteDataJdbc
io.aiven.klaw.service.ServerConfigService
io.aiven.klaw.service.UsersTeamsControllerService
io.aiven.klaw.service.CommonUtilsService
io.aiven.klaw.clusterapi.UtilMethods
---

Stats
Precision: 0.7
Recall: 0.875
Accuracy: 0.7714285714285715
F1 score: 0.7777777777777777
-------------
```

## Remove words: no, names multiply: no

```
False negatives: 2
io.aiven.klaw.clusterapi.controller.ClusterApiController
io.aiven.klaw.service.UtilControllerService
---
True negatives: 10
io.aiven.klaw.clusterapi.services.ConfluentCloudApiService
io.aiven.klaw.MockMethods
io.aiven.klaw.repository.MessageSchemaRepo
io.aiven.klaw.controller.AclController
io.aiven.klaw.repository.KwKafkaConnectorRepo
io.aiven.klaw.controller.TopicController
io.aiven.klaw.controller.KafkaConnectController
io.aiven.klaw.service.AnalyticsControllerService
io.aiven.klaw.service.MailUtils
io.aiven.klaw.service.ClusterApiService
---
False positives: 9
io.aiven.klaw.controller.SchemaRegistryController
io.aiven.klaw.repository.AclRequestsRepo
io.aiven.klaw.repository.AclRepo
io.aiven.klaw.repository.ActivityLogRepo
io.aiven.klaw.repository.KwKafkaConnectorRequestsRepo
io.aiven.klaw.repository.TopicRequestsRepo
io.aiven.klaw.repository.SchemaRequestRepo
io.aiven.klaw.repository.RegisterInfoRepo
io.aiven.klaw.repository.TopicRepo
---
True positives: 14
io.aiven.klaw.clusterapi.utils.ClusterApiUtils
io.aiven.klaw.UtilMethods
io.aiven.klaw.helpers.HandleDbRequests
io.aiven.klaw.controller.TemplateMapController
io.aiven.klaw.controller.UsersTeamsController
io.aiven.klaw.controller.EnvsClustersTenantsController
io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc
io.aiven.klaw.helpers.db.rdbms.HandleDbRequestsJdbc
io.aiven.klaw.helpers.db.rdbms.InsertDataJdbc
io.aiven.klaw.helpers.db.rdbms.DeleteDataJdbc
io.aiven.klaw.service.ServerConfigService
io.aiven.klaw.service.UsersTeamsControllerService
io.aiven.klaw.service.CommonUtilsService
io.aiven.klaw.clusterapi.UtilMethods
---

Stats
Precision: 0.6086956521739131
Recall: 0.875
Accuracy: 0.6857142857142857
F1 score: 0.717948717948718
-------------
```

## Remove words: no, names multiply: 1.3
```
False negatives: 2
io.aiven.klaw.clusterapi.controller.ClusterApiController
io.aiven.klaw.service.UtilControllerService
---
True negatives: 9
io.aiven.klaw.clusterapi.services.ConfluentCloudApiService
io.aiven.klaw.MockMethods
io.aiven.klaw.repository.ActivityLogRepo
io.aiven.klaw.controller.AclController
io.aiven.klaw.repository.KwKafkaConnectorRepo
io.aiven.klaw.controller.TopicController
io.aiven.klaw.controller.KafkaConnectController
io.aiven.klaw.service.AnalyticsControllerService
io.aiven.klaw.service.MailUtils
---
False positives: 10
io.aiven.klaw.controller.SchemaRegistryController
io.aiven.klaw.repository.AclRequestsRepo
io.aiven.klaw.repository.MessageSchemaRepo
io.aiven.klaw.repository.AclRepo
io.aiven.klaw.repository.KwKafkaConnectorRequestsRepo
io.aiven.klaw.repository.TopicRequestsRepo
io.aiven.klaw.repository.SchemaRequestRepo
io.aiven.klaw.repository.RegisterInfoRepo
io.aiven.klaw.repository.TopicRepo
io.aiven.klaw.service.ClusterApiService
---
True positives: 14
io.aiven.klaw.clusterapi.utils.ClusterApiUtils
io.aiven.klaw.UtilMethods
io.aiven.klaw.helpers.HandleDbRequests
io.aiven.klaw.controller.TemplateMapController
io.aiven.klaw.controller.UsersTeamsController
io.aiven.klaw.controller.EnvsClustersTenantsController
io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc
io.aiven.klaw.helpers.db.rdbms.HandleDbRequestsJdbc
io.aiven.klaw.helpers.db.rdbms.InsertDataJdbc
io.aiven.klaw.helpers.db.rdbms.DeleteDataJdbc
io.aiven.klaw.service.ServerConfigService
io.aiven.klaw.service.UsersTeamsControllerService
io.aiven.klaw.service.CommonUtilsService
io.aiven.klaw.clusterapi.UtilMethods
---

Stats
Precision: 0.5833333333333334
Recall: 0.875
Accuracy: 0.6571428571428571
F1 score: 0.7000000000000001
```

## Remove words: yes, signature multiply: 1.3

```
False negatives: 1
io.aiven.klaw.clusterapi.controller.ClusterApiController
---
True negatives: 10
io.aiven.klaw.clusterapi.services.ConfluentCloudApiService
io.aiven.klaw.MockMethods
io.aiven.klaw.controller.SchemaRegistryController
io.aiven.klaw.repository.MessageSchemaRepo
io.aiven.klaw.repository.KwKafkaConnectorRepo
io.aiven.klaw.controller.TopicController
io.aiven.klaw.repository.SchemaRequestRepo
io.aiven.klaw.controller.KafkaConnectController
io.aiven.klaw.service.MailUtils
io.aiven.klaw.service.ClusterApiService
---
False positives: 9
io.aiven.klaw.repository.AclRequestsRepo
io.aiven.klaw.repository.AclRepo
io.aiven.klaw.repository.ActivityLogRepo
io.aiven.klaw.controller.AclController
io.aiven.klaw.repository.KwKafkaConnectorRequestsRepo
io.aiven.klaw.repository.TopicRequestsRepo
io.aiven.klaw.repository.RegisterInfoRepo
io.aiven.klaw.repository.TopicRepo
io.aiven.klaw.service.AnalyticsControllerService
---
True positives: 15
io.aiven.klaw.clusterapi.utils.ClusterApiUtils
io.aiven.klaw.UtilMethods
io.aiven.klaw.helpers.HandleDbRequests
io.aiven.klaw.controller.TemplateMapController
io.aiven.klaw.controller.UsersTeamsController
io.aiven.klaw.controller.EnvsClustersTenantsController
io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc
io.aiven.klaw.helpers.db.rdbms.HandleDbRequestsJdbc
io.aiven.klaw.helpers.db.rdbms.InsertDataJdbc
io.aiven.klaw.helpers.db.rdbms.DeleteDataJdbc
io.aiven.klaw.service.ServerConfigService
io.aiven.klaw.service.UsersTeamsControllerService
io.aiven.klaw.service.UtilControllerService
io.aiven.klaw.service.CommonUtilsService
io.aiven.klaw.clusterapi.UtilMethods
---

Stats
Precision: 0.625
Recall: 0.9375
Accuracy: 0.7142857142857143
F1 score: 0.75
```


# TODO
- Extract LCOM4 for Klaw with delombok and newest jena
- Try combination of optimal_k > 2 and lcom4
- Try graphcodebert for method bodies + signatures

In [12]:
input_file = (
    "/media/martin/BigData/datasets/pa165-git/multi-service-filtered-labeled.jsonl"
)

df = read_json(input_file, lines=True)

df.query("label == 0 and len(methods) > 10")

ValueError: "len" is not a supported function